// === INTERSHIP ===
export const GET_INTERSHIP_LIST = 'GET_INTERSHIP_LIST';

export const GET_COURSE_LIST = 'GET_COURSE_LIST';

export const CREATE_NEW_INTERN = 'CREATE_NEW_INTERN';

export const UPDATE_INTERN = 'UPDATE_INTERN';

export const DELETE_INTERN = 'DELETE_INTERN';

export const ADD_DATA_TO_API = 'ADD_DATA_TO_API'
